/*
 * GovPay - Porta di Accesso al Nodo dei Pagamenti SPC
 * http://www.gov4j.it/govpay
 *
 * Copyright (c) 2014-2026 Link.it srl (http://www.link.it).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package it.govpay.pagamento.v3.api.impl;

import java.net.URLDecoder;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.Map;

import jakarta.servlet.http.HttpSession;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.Response.Status;

import org.openspcoop2.generic_project.exception.ServiceException;
import org.openspcoop2.utils.service.context.ContextThreadLocal;
import org.springframework.security.core.Authentication;

import it.govpay.bd.BDConfigWrapper;
import it.govpay.bd.model.Rpt;
import it.govpay.bd.model.Versamento;
import it.govpay.core.autorizzazione.AuthorizationManager;
import it.govpay.core.autorizzazione.beans.GovpayLdapUserDetails;
import it.govpay.core.autorizzazione.utils.AutorizzazioneUtils;
import it.govpay.core.dao.pagamenti.RptDAO;
import it.govpay.core.dao.pagamenti.dto.LeggiRicevutaDTO;
import it.govpay.core.dao.pagamenti.dto.LeggiRicevutaDTO.FormatoRicevuta;
import it.govpay.core.dao.pagamenti.dto.LeggiRicevutaDTOResponse;
import it.govpay.core.exceptions.NotAcceptableException;
import it.govpay.core.exceptions.NotAuthorizedException;
import it.govpay.core.utils.GovpayConfig;
import it.govpay.core.utils.validator.ValidatoreIdentificativi;
import it.govpay.model.Acl.Diritti;
import it.govpay.model.Acl.Servizio;
import it.govpay.model.Utenza.TIPO_UTENZA;
import it.govpay.pagamento.v2.controller.BaseController;
import it.govpay.pagamento.v3.api.RicevuteApi;
import it.govpay.pagamento.v3.beans.Ricevuta;
import it.govpay.pagamento.v3.beans.converter.RicevuteConverter;


/**
 * GovPay - API Pagamento
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
@Deprecated(since = "3.9.0", forRemoval = true)
public class RicevuteApiServiceImpl extends BaseApiServiceImpl implements RicevuteApi {


	public RicevuteApiServiceImpl() {
		super("ricevute", RicevuteApiServiceImpl.class);
	}

	/**
	 * Acquisizione di una ricevuta di avvenuto pagamento pagoPA
	 *
	 * Ricevuta pagoPA, sia questa veicolata nella forma di &#x60;RT&#x60; o di &#x60;recepit&#x60;, di esito positivo.
	 *
	 */
	@Override
	public Response getRicevuta(String idDominio, String iuv, String idRicevuta) {
		this.buildContext();
		Authentication user = this.getUser();
		String methodName = "getRicevuta";
		String transactionId = ContextThreadLocal.get().getTransactionId();
		this.logDebug(BaseApiServiceImpl.LOG_MSG_ESECUZIONE_METODO_IN_CORSO, methodName);

		String accept = "";
		if(httpHeaders.getRequestHeaders().containsKey("Accept")) {
			accept = httpHeaders.getRequestHeaders().get("Accept").get(0).toLowerCase();
		}
		try{
			// autorizzazione sulla API
			this.isAuthorized(user, Arrays.asList(TIPO_UTENZA.ANONIMO, TIPO_UTENZA.CITTADINO, TIPO_UTENZA.APPLICAZIONE), Arrays.asList(Servizio.API_PAGAMENTI), Arrays.asList(Diritti.LETTURA));

			ValidatoreIdentificativi validatoreId = ValidatoreIdentificativi.newInstance();
			validatoreId.validaIdDominio("idDominio", idDominio);

			LeggiRicevutaDTO leggiRptDTO = new LeggiRicevutaDTO(user);
			leggiRptDTO.setIdDominio(idDominio);
			leggiRptDTO.setIuv(iuv);
			idRicevuta = idRicevuta.contains("%") ? URLDecoder.decode(idRicevuta,"UTF-8") : idRicevuta;
			leggiRptDTO.setCcp(idRicevuta);

			RptDAO ricevuteDAO = new RptDAO();

			LeggiRicevutaDTOResponse ricevutaDTOResponse = null;
			if(accept.toLowerCase().contains("application/pdf")) {
				leggiRptDTO.setFormato(FormatoRicevuta.PDF);
				ricevutaDTOResponse = ricevuteDAO.leggiRt(leggiRptDTO);
				String rtPdfEntryName = idDominio +"_"+ iuv + "_"+ idRicevuta + ".pdf";
				byte[] b = ricevutaDTOResponse.getPdf();

				checkAutorizzazioniUtenza(leggiRptDTO.getUser(), ricevutaDTOResponse.getRpt());
				this.logDebug(BaseApiServiceImpl.LOG_MSG_ESECUZIONE_METODO_COMPLETATA, methodName);
				return this.handleResponseOk(Response.status(Status.OK).type("application/pdf").entity(b).header("content-disposition", "attachment; filename=\""+rtPdfEntryName+"\""),transactionId).build();
			} else if(accept.toLowerCase().contains(MediaType.APPLICATION_JSON)) {
				leggiRptDTO.setFormato(FormatoRicevuta.JSON);
				ricevutaDTOResponse = ricevuteDAO.leggiRt(leggiRptDTO);

				checkAutorizzazioniUtenza(leggiRptDTO.getUser(), ricevutaDTOResponse.getRpt());

				Ricevuta response =  RicevuteConverter.toRsModel(ricevutaDTOResponse.getRpt(), user);

				return this.handleResponseOk(Response.status(Status.OK).entity(response),transactionId).build();
			} else {
				// formato non accettato
				throw new NotAcceptableException("Avviso di pagamento non disponibile nel formato indicato nell'header Accept, ricevuto: '"+accept+"', consentiti: {'application/pdf','application/json'}");

			}
		}catch (Exception e) {
			return this.handleException(uriInfo, httpHeaders, methodName, e, transactionId);
		} finally {
			this.logContext(ContextThreadLocal.get());
		}
	}

	@SuppressWarnings("unchecked")
	private void checkAutorizzazioniUtenza(Authentication user, Rpt rpt) throws ServiceException, NotAuthorizedException {
		BDConfigWrapper configWrapper = new BDConfigWrapper(ContextThreadLocal.get().getTransactionId(), true);
		Versamento versamento = rpt.getVersamento();
		GovpayLdapUserDetails details = AutorizzazioneUtils.getAuthenticationDetails(user);
		if(details.getTipoUtenza().equals(TIPO_UTENZA.CITTADINO)) {
			if(!versamento.getAnagraficaDebitore().getCodUnivoco().equals(details.getUtenza().getIdentificativo())) {
				throw AuthorizationManager.toNotAuthorizedException(user, "la transazione riferisce una  pendenza che non appartiene al cittadino chiamante");
			}
		}

		if(details.getTipoUtenza().equals(TIPO_UTENZA.ANONIMO)) {
			// pagamento terminato e' disponibile solo per un numero di minuti definito in configurazione
			if(rpt.getDataMsgRicevuta() != null) {
				long dataPagamentoTime = rpt.getDataMsgRicevuta().getTime();
				Calendar calendar = Calendar.getInstance();
				calendar.setTime(new Date());
				calendar.add(Calendar.MINUTE, -GovpayConfig.getInstance().getIntervalloDisponibilitaPagamentoUtenzaAnonima());
				long riferimentoTime = calendar.getTimeInMillis();

				// il pagamento e' stato eseguito prima dei minuti precedenti il momento della richiesta.
				if(dataPagamentoTime < riferimentoTime)
					throw AuthorizationManager.toNotAuthorizedException(user);
			}

			Map<String, Versamento> listaIdentificativi = null;
			Map<String, String> listaAvvisi = null;
			Versamento versamentoFromSession = null;
			// leggere dalla sessione gli id pendenza per iuv-dominio
			HttpSession session = this.request.getSession(false);
			if(session!= null) {
				listaIdentificativi = (Map<String, Versamento>) session.getAttribute(BaseController.PENDENZE_CITTADINO_ATTRIBUTE);

				String chiaveAvviso = rpt.getCodDominio()+rpt.getIuv();
				if(rpt.getIuv().length() == 18) {
					listaAvvisi = (Map<String, String>) session.getAttribute(BaseController.AVVISI_CITTADINO_ATTRIBUTE);
				} else {
					listaAvvisi = (Map<String, String>) session.getAttribute(BaseController.IUV_CITTADINO_ATTRIBUTE);
				}

				if(listaAvvisi != null && listaAvvisi.size() > 0) {
					if(listaAvvisi.containsKey(chiaveAvviso)) {
						String chiavePendenza = listaAvvisi.get(chiaveAvviso);

						if(listaIdentificativi.containsKey(chiavePendenza)) {
							versamentoFromSession = listaIdentificativi.get(chiavePendenza);
						}
					}
				}
			}

			if(versamentoFromSession == null) {
				// non ho trovato una pendenza nella sessione
				throw AuthorizationManager.toNotAuthorizedException(user, "la transazione riferisce una pendenza che non appartiene all'applicazione chiamante");
			}
		}

		// se sei una applicazione allora vedi i pagamenti che hai caricato
		if(details.getTipoUtenza().equals(TIPO_UTENZA.APPLICAZIONE)) {
			if(!versamento.getApplicazione(configWrapper).getCodApplicazione().equals(details.getApplicazione().getCodApplicazione())) {
				throw AuthorizationManager.toNotAuthorizedException(user, "la transazione riferisce una pendenza che non appartiene all'applicazione chiamante");
			}
		}
	}
}
